/* eslint-disable */
export default {
    kdt_id: 55,
    user_id: 4674509,
    offline_id: 0,
    activity_alias: '',
    sku: {
      tree: [],
      list: [],
      price: '1.00',
      stock_num: 227,
      collection_id: 2261,
      collection_price: 0,
      none_sku: false,
      sold_num: 0,
      min_price: '1.00',
      max_price: '1.00',
      messages: [
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: '0',
          name: 'PO号',
          disable_required: false,
          disable_edit_name: false,
          type: 'poNum',
          disable_delete: false,
          disable_type: false,
          required: 0,
          
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: '0',
          name: '纸质',
          disable_required: false,
          disable_edit_name: false,
          type: 'zhiZhi',
          disable_delete: false,
          disable_type: false,
          required: 1,
          
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: '0',
          name: '楞别',
          disable_required: false,
          disable_edit_name: false,
          type: 'lengBie',
          disable_delete: false,
          disable_type: false,
          required: 1,
          
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: '0',
          name: '纸长(mm)',
          disable_required: false,
          disable_edit_name: false,
          type: 'zhiLength',
          disable_delete: false,
          disable_type: false,
          required: '1',
          
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '纸宽(mm)',
          disable_required: false,
          disable_edit_name: false,
          type: 'zhiWide',
          disable_delete: false,
          disable_type: false,
          required: 1
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '数量(片)',
          disable_required: false,
          disable_edit_name: false,
          type: 'tel',
          disable_delete: false,
          disable_type: false,
          required: 1
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '箱高(mm)',
          disable_required: false,
          disable_edit_name: false,
          type: 'xianggo',
          disable_delete: false,
          disable_type: false,
          required: 0
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '压线',
          disable_required: false,
          disable_edit_name: false,
          type: 'yaxian',
          disable_delete: false,
          disable_type: false,
          required: 0
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '压线类型',
          disable_required: false,
          disable_edit_name: false,
          type: 'yaxianType',
          disable_delete: false,
          disable_type: false,
          required: 1
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 0,
          name: '交货日期',
          disable_required: false,
          disable_edit_name: false,
          type: 'date',
          disable_delete: false,
          disable_type: false,
          required: 0
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 1,
          name: '送货备注',
          disable_required: false,
          disable_edit_name: false,
          type: 'text',
          disable_delete: false,
          disable_type: false,
          required: 0
        },
        {
          datetime: '0',
          disable_multiple: false,
          disable: false,
          multiple: 1,
          name: '生产备注',
          disable_required: false,
          disable_edit_name: false,
          type: 'text',
          disable_delete: false,
          disable_type: false,
          required: 0
        },
       
      ],
      hide_stock: true
    },
    goods_id: '00000',
    alias: '0000',
    quota: 0,
    is_virtual: '0',
    quota_used: 0,
    goods_info: {
      title: '商品名称',
      picture:'',
      price: 1,
      origin: '10'
    }
  };